### ISSUE TITLE
Map files ending with 1 can't be extracted

### ISSUE THREAD

**Issue by CIB** [SnowSzn/rgss-db-cli#1]
lib/rgss_db/model/data_file.rb
```rb
  # RPG Maker maps data file (glob pattern)
  # @return [String]
  DATA_FILE_MAPS = "Map[0-9][0-9][1-9]"
```

For example `Map010.rvdata2` will never be recognized by the tool since it doesn't match the glob pattern.

**Comment by SnowSzn** [comment]
> lib/rgss_db/model/data_file.rb
> 
> ```ruby
>   # RPG Maker maps data file (glob pattern)
>   # @return [String]
>   DATA_FILE_MAPS = "Map[0-9][0-9][1-9]"
> ```
> 
> For example `Map010.rvdata2` will never be recognized by the tool since it doesn't match the glob pattern.

Yeah, you are right, I just pushed a quick update to fix the glob pattern, it should detect all map files now

**Comment by CIB** [comment]
Thanks! I checked the commit, and it's the same change I did locally to get it to work for me.
